language: java
install:
  - mvn dependency:resolve
matrix:
  include:
    jdk: oraclejdk8
    script: mvn clean package
  include:
    jdk: oraclejdk7
    script: mvn clean package -Dmaven.test.skip=true
